export type ScalarMap = Record<string, number>;
export interface NeuronSample { neuron?: number; body_id?: number | string; rate_hz?: number; activity?: number; position?: [number,number,number]; x?:number;y?:number;z?:number; cell_type?:string; region?:string }
export interface Population { size?: number; mean_rate_hz?: number; activity?:number; sampled?: NeuronSample[]; contributing_actions?: string[] }
export interface ReplayStep { kind:string; t_ms:number; controller_step?:number; episode_tic?:number; frame_index?:number; frame?:string; state?:Record<string,unknown>; jev?:{request_id?:string;probabilities?:ScalarMap;questions?:Array<{question:string;probability?:number;score?:number}>;latency_ms?:number;model?:string;is_mock?:boolean;confidence?:number;decision?:string}; populations?:Record<string,Population>; neurons?:NeuronSample[]; motor?:{scores?:ScalarMap;selected?:string;selected_action?:string;confidence?:number;raw_rates?:ScalarMap;contributing_populations?:Record<string,string[]>}; reward?:number; controller_latency_ms?:number }
export interface FramesMeta {kind:string;file?:string;count?:number;shape?:number[];dtype?:string;downsample?:number;format?:string;files?:string[];timestamps_ms?:number[]}
export interface RecordingHeader {kind:string;recording_format_version?:string;created_at?:number|string;seed?:number;software_version?:string;environment_backend?:string;warnings?:string[];config?:Record<string,unknown>;connectome?:{provenance?:unknown;populations?:Record<string,unknown>};jev?:Record<string,unknown>;bridge?:Record<string,unknown>;motor?:Record<string,unknown>}
export interface Recording {id:string; title:string; subtitle:string; path:string; header:RecordingHeader;steps:ReplayStep[];frames?:FramesMeta;duration:number;frameData?:Uint8Array;metrics:RunMetrics}
export interface RunMetrics {duration:number;steps:number;kills:number;health:number;ammo:number;meanConfidence:number;meanLatency:number;reward:number;actions:Record<string,number>}
export interface CatalogItem {id:string;title:string;subtitle:string;path:string;featured?:boolean}
