"""Export structural recordings as a Hugging Face-ready dataset directory.

Usage:

    python -m flydoom.export.hf [recordings_dir] [out_dir]

Defaults: outputs/recordings -> outputs/hf_dataset.

Layout produced (directly pushable as a HF *dataset* repo — the hub converts
the JSONL shards to parquet automatically on push):

    README.md                  dataset card (YAML frontmatter + description)
    data/episodes.jsonl        one row per episode: id, controller, scenario,
                               seed, outcome stats (survival_s, kills, ...)
    data/steps-00000.jsonl.gz  one row per controller step: game state, motor
                               decision (selected/combo/attack_spiked/
                               attack_assisted/aim_ok), Jev block (nullable),
                               neural totals, retinal drive, top-K activity,
                               plus episode_id + frame_file
    frames/<episode_id>/*.jpg  the actual DOOM frames
    frames/metadata.jsonl      imagefolder-compatible index (file_name +
                               episode_id + action labels)

Frames are hardlinked (copy fallback) so the export costs ~no extra disk on
the same volume. Re-runs are incremental: episodes already present in
data/episodes.jsonl are skipped.
"""

from __future__ import annotations

import argparse
import gzip
import json
import os
import shutil
import sys
from pathlib import Path

SHARD_STEPS = 20000  # controller steps per compressed shard

CARD = """---
license: mit
task_categories:
  - reinforcement-learning
tags:
  - neuroscience
  - connectomics
  - drosophila
  - malecns
  - vizdoom
  - doom
  - spiking-neural-networks
pretty_name: Fly-DOOM-Jev
configs:
  - config_name: episodes
    data_files: data/episodes.jsonl
  - config_name: steps
    data_files: data/steps-*.jsonl.gz
---

# Fly-DOOM-Jev

Closed-loop recordings of the complete MaleCNS v1.0 *Drosophila* connectome
(211,577 neurons, spiking LIF simulation) playing ViZDoom, with and without
the Jev probabilistic decision layer biasing action classes.

- `episodes`: one row per episode (controller, scenario, seed, outcome stats).
- `steps`: one row per controller step — game state, motor decision
  (`selected`, `combo`, `attack_spiked`, `attack_assisted`, `aim_ok`), the Jev
  decision block (null for brain-only runs), neural spike totals, retinal
  drive, and the top-K most-active neurons with firing rates.
- `frames/`: the actual game frames (JPEG), indexed by `frames/metadata.jsonl`.

The connectome wiring is biological reconstruction data (MaleCNS v1.0); the
neural dynamics, retinal interface, motor decoder, and reinforcement events
are engineering models, not measured fly physiology. Generated by
fly-doom-jev (https://github.com/Vaibhaav-Tiwari/fly-doom-jev).
"""


def _link_or_copy(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists():
        return
    try:
        os.link(src, dst)
    except OSError:
        shutil.copy2(src, dst)


def _episode_row(ep_id: str, header: dict, end: dict | None,
                 n_steps: int, n_frames: int) -> dict:
    cfg = header.get("config", {})
    env = cfg.get("environment", {})
    ep = (end or {}).get("episode", {})
    return {"episode_id": ep_id,
            "created_at": header.get("created_at"),
            "controller": header.get("controller"),
            "run_kind": header.get("run_kind"),
            "seed": header.get("seed"),
            "scenario": env.get("scenario"),
            "skill": env.get("skill"),
            "recording_format_version": header.get("recording_format_version"),
            "controller_steps": ep.get("controller_steps", n_steps),
            "survival_s": ep.get("survival_s"),
            "duration_s": ep.get("duration_s"),
            "kills": ep.get("kills"),
            "health_end": ep.get("health_end"),
            "ammo_end": ep.get("ammo_end"),
            "total_reward": ep.get("total_reward"),
            "reset_reason": ep.get("reset_reason"),
            "jev_decisions": ep.get("jev_decisions"),
            "jev_tokens": ep.get("jev_tokens"),
            "frame_count": n_frames}


def _step_rows(ep_id: str, step: dict) -> dict:
    st = step.get("state") or {}
    mo = step.get("motor") or {}
    jev = step.get("jev")
    ne = step.get("neural") or {}
    return {"episode_id": ep_id,
            "controller_step": step.get("controller_step"),
            "t_ms": step.get("t_ms"),
            "episode_tic": step.get("episode_tic"),
            "frame_file": f"frames/{ep_id}/{os.path.basename(str(step.get('frame_ref') or ''))}" or None,
            "health": st.get("health"), "ammo": st.get("ammo"),
            "kills": st.get("kills"),
            "enemy_visible": st.get("enemy_visible"),
            "enemy_distance": st.get("enemy_distance"),
            "enemy_angle": st.get("enemy_angle"),
            "aim_offset_deg": st.get("aim_offset_deg"),
            "threat_level": st.get("threat_level"),
            "position_x": st.get("position_x"),
            "position_y": st.get("position_y"),
            "alive_s": st.get("alive_s"),
            "selected": mo.get("selected"), "combo": mo.get("combo"),
            "confidence": mo.get("confidence"),
            "aim_ok": mo.get("aim_ok"),
            "attack_spiked": mo.get("attack_spiked"),
            "attack_assisted": mo.get("attack_assisted"),
            "unstuck": mo.get("unstuck"),
            "jev_weights": mo.get("jev_weights"),
            "jev": jev,
            "total_spikes": ne.get("total_spikes"),
            "neural_time_ms": ne.get("time_ms"),
            "retina": step.get("retina"),
            "activity_top": (step.get("activity") or {}).get("top"),
            "populations": (step.get("activity") or {}).get("populations")}


class _ShardWriter:
    def __init__(self, data_dir: Path):
        self.data_dir = data_dir
        self.n = 0
        self.shard = -1
        self._fh = None

    def _open_next(self):
        if self._fh:
            self._fh.close()
        self.shard += 1
        path = self.data_dir / f"steps-{self.shard:05d}.jsonl.gz"
        self._fh = gzip.open(path, "wt", encoding="utf-8")

    def write(self, row: dict) -> None:
        if self._fh is None or self.n % SHARD_STEPS == 0:
            self._open_next()
        self._fh.write(json.dumps(row) + "\n")
        self.n += 1

    def close(self):
        if self._fh:
            self._fh.close()


def export(recordings_dir: Path, out_dir: Path) -> dict:
    data_dir = out_dir / "data"
    frames_dir = out_dir / "frames"
    data_dir.mkdir(parents=True, exist_ok=True)
    frames_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "README.md").write_text(CARD)

    ep_path = data_dir / "episodes.jsonl"
    done = set()
    if ep_path.exists():
        for line in ep_path.read_text().splitlines():
            if line.strip():
                done.add(json.loads(line)["episode_id"])

    episodes = []
    for d in sorted(recordings_dir.iterdir()):
        rec = d / "recording.jsonl"
        if not (d.is_dir() and rec.exists()) or d.name in done:
            continue
        header, end, n_steps = None, None, 0
        with rec.open() as fh:
            for line in fh:
                r = json.loads(line)
                if r.get("kind") == "header":
                    header = r
                elif r.get("kind") == "episode_end":
                    end = r
                elif r.get("kind") == "step":
                    n_steps += 1
        if header is None or end is None:
            continue  # incomplete episode (still recording or aborted)
        frames = sorted((d / "frames").glob("*.jpg")) if (d / "frames").is_dir() else []
        episodes.append((d, header, end, n_steps, len(frames)))

    shards = _ShardWriter(data_dir)
    meta_fh = (frames_dir / "metadata.jsonl").open("a", encoding="utf-8")
    ep_fh = ep_path.open("a", encoding="utf-8")
    stats = {"episodes_exported": 0, "steps_exported": 0, "frames_linked": 0}
    for d, header, end, n_steps, n_frames in episodes:
        ep_id = d.name
        with (d / "recording.jsonl").open() as fh:
            for line in fh:
                r = json.loads(line)
                if r.get("kind") != "step":
                    continue
                row = _step_rows(ep_id, r)
                shards.write(row)
                stats["steps_exported"] += 1
                if r.get("frame_ref"):
                    src = d / str(r["frame_ref"])
                    dst = frames_dir / ep_id / src.name
                    _link_or_copy(src, dst)
                    meta_fh.write(json.dumps(
                        {"file_name": f"{ep_id}/{src.name}",
                         "episode_id": ep_id,
                         "controller_step": r.get("controller_step"),
                         "selected": (r.get("motor") or {}).get("selected"),
                         "attack": "attack" in ((r.get("motor") or {}).get("combo") or [])}) + "\n")
                    stats["frames_linked"] += 1
        ep_fh.write(json.dumps(_episode_row(ep_id, header, end, n_steps, n_frames)) + "\n")
        stats["episodes_exported"] += 1
    shards.close()
    meta_fh.close()
    ep_fh.close()
    return stats


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("recordings", nargs="?", default="outputs/recordings")
    ap.add_argument("out", nargs="?", default="outputs/hf_dataset")
    args = ap.parse_args(argv)
    stats = export(Path(args.recordings), Path(args.out))
    print(json.dumps(stats))
    return 0


if __name__ == "__main__":
    sys.exit(main())
