import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Activity,Brain,ChevronDown,Database,FlaskConical,Code2,Info,Layers3,Radio,TimerReset} from 'lucide-react';
import type {CatalogItem,Recording} from './lib/types';
import {loadCatalog,loadRecording,nearestStep,pct} from './lib/recording';
import Panel from './components/Panel';import DoomViewport from './components/DoomViewport';import BrainView from './components/BrainView';import JevPanel from './components/JevPanel';import MotorPanel from './components/MotorPanel';import Timeline from './components/Timeline';

export default function App(){
 const [catalog,setCatalog]=useState<CatalogItem[]>([]),[recordings,setRecordings]=useState<Record<string,Recording>>({}),[selected,setSelected]=useState(''),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[error,setError]=useState('');const raf=useRef(0),last=useRef(0);
 useEffect(()=>{loadCatalog().then(async items=>{setCatalog(items);setSelected(items[0]?.id??'');const loaded=await Promise.all(items.map(loadRecording));setRecordings(Object.fromEntries(loaded.map(r=>[r.id,r])))}).catch(e=>setError(e.message))},[]);
 const recording=recordings[selected],step=recording?nearestStep(recording.steps,time):null,stepIndex=recording&&step?recording.steps.indexOf(step):0,history=recording?.steps.slice(Math.max(0,stepIndex-12),stepIndex+1)??[];
 const seek=useCallback((v:number)=>{setTime(Math.max(0,Math.min(recording?.duration??0,v)))},[recording]);
 useEffect(()=>{if(!playing||!recording)return;last.current=performance.now();const tick=(now:number)=>{const delta=(now-last.current)*speed;last.current=now;setTime(t=>{const next=t+delta;if(next>=recording.duration){setPlaying(false);return recording.duration}return next});raf.current=requestAnimationFrame(tick)};raf.current=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf.current)},[playing,recording,speed]);
 useEffect(()=>{setTime(0);setPlaying(false)},[selected]);
 const aggregate=useMemo(()=>recording?.metrics,null as any);
 if(error)return <main className="loading"><h1>Recording unavailable</h1><p>{error}</p></main>;
 if(!recording)return <main className="loading"><div className="loader"/><p>Indexing recorded experiments…</p></main>;
 const s=step?.state??{};const warnings=recording.header.warnings??[];
 return <div className="app">
  <header className="topbar"><a className="brand" href="#"><div className="mark"><Brain/></div><div><strong>JEV × FLY</strong><span>IN DOOM</span></div></a><div className="mode-badge"><span/><b>RECORDED EXPERIMENT</b><small>STATIC REPLAY · NO API</small></div><nav><a href="#method">Method</a><a href="#metrics">Runs</a><a href="#about">About</a><a className="icon-link" href="https://github.com/Vaibhaav-Tiwari/fly-doom-jev" aria-label="GitHub"><Code2/></a></nav></header>
  <main><section className="intro"><div><div className="eyebrow"><FlaskConical/> MALECNS v1.0 · PROBABILISTIC DECISION CONTROL</div><h1>A fly connectome.<br/><em>A decision model.</em> DOOM.</h1><p>Replay a synchronized experiment—from visual observation through Jev's probabilities, MaleCNS population activity, motor decoding, and the resulting game action.</p></div><div className="experiment-picker"><label>RECORDED EXPERIMENT</label><div className="select-shell"><Database/><select value={selected} onChange={e=>setSelected(e.target.value)}>{catalog.map(r=><option value={r.id} key={r.id}>{r.title}</option>)}</select><ChevronDown/></div><span>{recording.subtitle}</span><small>FORMAT v{recording.header.recording_format_version??'unknown'} · {recording.metrics.steps} synchronized steps</small></div></section>
  {warnings.length>0&&<div className="integrity-banner"><Info/><div><b>Scientific integrity note</b><span>{warnings.join(' · ')}</span></div></div>}
  <section className="dashboard">
   <Panel title="ViZDoom observation" kicker="01 · ENVIRONMENT" tools={<span className="status"><Radio/> Episode {String(s.episode_state??'replay')}</span>} className="doom-panel"><DoomViewport recording={recording} step={step}/></Panel>
   <Panel title="Jev decision state" kicker="02 · REASONING" tools={<span className="status"><TimerReset/> {step?.jev?.request_id??'No request ID'}</span>}><JevPanel step={step} history={history} onSeek={seek}/></Panel>
   <Panel title="MaleCNS activity" kicker="03 · CONNECTOME" tools={<span className="status"><Layers3/> {Object.keys(step?.populations??{}).length} populations</span>} className="brain-panel"><BrainView step={step}/></Panel>
   <Panel title="Motor decoder" kicker="04 · OUTPUT" tools={<span className="status"><Activity/> {Object.keys(step?.motor?.scores??{}).length} actions</span>}><MotorPanel step={step}/></Panel>
  </section>
  <Timeline recording={recording} time={time} playing={playing} speed={speed} onPlay={()=>setPlaying(x=>!x)} onSeek={seek} onSpeed={setSpeed}/>
  <section className="metrics" id="metrics"><div className="section-title"><span>EXPERIMENT COMPARISON</span><h2>Recorded run metrics</h2><p>Every number below is derived from the selected recording. Select another run to compare traces and outcomes.</p></div><div className="metric-grid"><Metric label="Duration" value={`${(aggregate.duration/1000).toFixed(1)} s`} sub={`${aggregate.steps} controller steps`}/><Metric label="Final health" value={aggregate.health.toFixed(0)} sub={`${aggregate.ammo.toFixed(0)} ammo remaining`}/><Metric label="Mean confidence" value={pct(aggregate.meanConfidence)} sub="motor decoder"/><Metric label="Jev latency" value={`${aggregate.meanLatency.toFixed(1)} ms`} sub="mean recorded latency"/><Metric label="Total reward" value={aggregate.reward.toFixed(2)} sub={`${aggregate.kills} kills`}/></div><div className="run-table"><div className="run-row head"><span>Run</span><span>Steps</span><span>Confidence</span><span>Latency</span><span>Outcome</span></div>{Object.values(recordings).map(r=><button className={`run-row ${r.id===selected?'active':''}`} onClick={()=>setSelected(r.id)} key={r.id}><span><i/>{r.title}<small>{r.subtitle}</small></span><span>{r.metrics.steps}</span><span>{pct(r.metrics.meanConfidence)}</span><span>{r.metrics.meanLatency.toFixed(1)} ms</span><span>{r.metrics.kills} kills · {r.metrics.health.toFixed(0)} HP</span></button>)}</div></section>
  <section className="method" id="method"><div><span>REPLAY-FIRST ARCHITECTURE</span><h2>Transparent by design.</h2></div><p>This public demo reads static recording files directly in your browser. It does not contact Jev, execute ViZDoom, or simulate the connectome. Observed activity, decoded outputs, and engineering annotations are labeled separately.</p><div className="flow"><b>Recorded DOOM frame</b><i>→</i><b>Jev probabilities</b><i>→</i><b>MaleCNS activity</b><i>→</i><b>Motor output</b></div></section>
  </main><footer id="about"><span>JEV × FLY IN DOOM</span><p>A replay interface for computational neuroscience experiments.</p><small>Data shown exactly as recorded · Build 2026.09</small></footer>
 </div>
}
function Metric({label,value,sub}:{label:string;value:string;sub:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
