import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {BrainCircuit,ChevronDown,Database,ExternalLink,Heart,Info,Play,Skull,Volume2,Zap} from 'lucide-react';
import type {CatalogItem,Recording} from './lib/types';
import {loadCatalog,loadRecording,nearestStep,pct} from './lib/recording';
import BrainView from './components/BrainView';import DoomViewport from './components/DoomViewport';import ActionTimeline from './components/ActionTimeline';
const actionColor:Record<string,string>={attack:'#c77979',forward:'#a8b9aa',turn_left:'#a391c5',turn_right:'#8fa9bb',noop:'#667075',retreat:'#c8a674'};
export default function App(){const [catalog,setCatalog]=useState<CatalogItem[]>([]),[runs,setRuns]=useState<Record<string,Recording>>({}),[selected,setSelected]=useState(''),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[focus,setFocus]=useState<string|null>(null),[error,setError]=useState('');const raf=useRef(0),last=useRef(0);
useEffect(()=>{loadCatalog().then(async c=>{setCatalog(c);setSelected(c[0]?.id??'');const all=await Promise.all(c.map(loadRecording));setRuns(Object.fromEntries(all.map(x=>[x.id,x])))}).catch(e=>setError(e.message))},[]);const recording=runs[selected],step=recording?nearestStep(recording.steps,time):null,action=step?.motor?.selected_action??step?.motor?.selected??'—';const seek=useCallback((t:number)=>setTime(Math.max(0,Math.min(recording?.duration??0,t))),[recording]);
useEffect(()=>{if(!playing||!recording)return;last.current=performance.now();const loop=(now:number)=>{const dt=(now-last.current)*speed;last.current=now;setTime(t=>{if(t+dt>=recording.duration){setPlaying(false);return recording.duration}return t+dt});raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf.current)},[playing,speed,recording]);useEffect(()=>{setTime(0);setPlaying(false)},[selected]);
const scores=Object.entries(step?.motor?.scores??{}).sort((a,b)=>b[1]-a[1]);const populations=Object.entries(step?.populations??{}).sort((a,b)=>(b[1].mean_rate_hz??0)-(a[1].mean_rate_hz??0));const thinking=Object.entries(step?.jev?.probabilities??{}).sort((a,b)=>b[1]-a[1]);const sourcePopulation=typeof recording.header.motor?.source_population==='string'?recording.header.motor.source_population:undefined;const contributors=step?.motor?.contributing_populations?.[action]??(sourcePopulation?[sourcePopulation]:[]);const effectiveFocus=focus??contributors[0]??null;const state=step?.state??{};
if(error)return <div className="load-screen"><Skull/><h1>Replay cartridge failed to load.</h1><p>{error}</p></div>;if(!recording)return <div className="load-screen"><BrainCircuit className="pulse"/><p>Waking up the fly brain…</p></div>;
return <div className="experience"><header><a className="logo" href="#"><BrainCircuit/><div><b>FLY//DOOM</b><small>JEV DRIVES A CONNECTOME</small></div></a><div className="recording-chip"><i/> PLAYING A RECORDING <span>NO API · NO SETUP</span></div><div className="run-select"><Database/><select value={selected} onChange={e=>setSelected(e.target.value)}>{catalog.map(x=><option value={x.id} key={x.id}>{x.title}</option>)}</select><ChevronDown/></div><a className="source" href="https://github.com/Vaibhaav-Tiwari/fly-doom-jev" target="_blank">SOURCE <ExternalLink/></a></header>
<main><div className="headline"><div><span>MEET THE PILOT</span><h1>211K neurons.<br/><em>One tiny gamer.</em></h1></div><p>Recorded signals ripple through a fruit fly connectome and become moves in DOOM. Hit play, then click an action to see the neurons behind it.</p><button onClick={()=>setPlaying(true)}><Play/> WATCH THE FLY THINK</button></div>
<section className="hero"><div className="brain-hero"><BrainView recording={recording} step={step} activePopulation={effectiveFocus} onPopulation={setFocus}/></div><div className="game-side"><div className="game-head"><span>DOOM // RECORDED FEED</span><div><i/> SYNCED</div></div><DoomViewport recording={recording} step={step}/><div className="game-stats"><div><Heart/><span>HEALTH</span><b>{Number(state.health??0).toFixed(0)}</b></div><div><Zap/><span>AMMO</span><b>{Number(state.ammo??0).toFixed(0)}</b></div><div><Skull/><span>KILLS</span><b>{Number(state.kills??0).toFixed(0)}</b></div></div></div></section>
<section className="signal-strip"><div className="current-action"><small>MOTOR OUTPUT</small><div style={{'--accent':actionColor[action]??'#a8b9aa'} as React.CSSProperties}><i/><strong>{action.replaceAll('_',' ')}</strong><span>{pct(step?.motor?.confidence??0)} confidence</span></div></div><div className="caused-by"><small>NEURAL DRIVE // CLICK TO ISOLATE</small><div>{contributors.length?contributors.map((p,i)=><button className={effectiveFocus===p?'active':''} onClick={()=>setFocus(focus===p?null:p)} key={p}><i style={{opacity:1-i*.25}}/>{p.replaceAll('_',' ')} <b>{Math.round(step?.populations?.[p]?.mean_rate_hz??0)} Hz</b></button>):<span>Contribution labels not present in this recording</span>}</div><p><Info/> Decoder contribution—not a claim of biological function.</p></div><div className="jev-glance"><small><Volume2/> JEV IS THINKING</small>{thinking.slice(0,3).map(([q,p])=><div key={q}><span>{q.replaceAll('_',' ')}</span><i><b style={{width:pct(p)}}/></i><em>{pct(p)}</em></div>)}</div><div className="scores"><small>ACTION SCORES</small>{scores.slice(0,5).map(([a,s])=><div className={a===action?'active':''} key={a}><span>{a.replaceAll('_',' ')}</span><b>{s.toFixed(2)}</b></div>)}</div></section>
<ActionTimeline recording={recording} time={time} playing={playing} speed={speed} onPlay={()=>setPlaying(x=>!x)} onSeek={seek} onSpeed={setSpeed}/><div className="data-note">REAL RECORDING · {recording.header.recording_format_version?'FORMAT '+recording.header.recording_format_version:'FORMAT UNKNOWN'} · {recording.metrics.steps} FRAMES · {recording.subtitle}</div></main></div>}
