import {useEffect,useMemo,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {Maximize2,MousePointer2,Sparkles} from 'lucide-react';
import type {Recording,ReplayStep,NeuronSample} from '../lib/types';
const palette:Record<string,string>={ol_sensory:'#9dafbd',visual_projection:'#b7c7d8',visual_centrifugal:'#8ba8b9',ol_intrinsic:'#9c8acb',cx_intrinsic:'#d6b27b',cb_intrinsic:'#c3aaa0',cb_sensory:'#92a998',ascending_neuron:'#aaa5bd',descending_neuron:'#e5ddd0',vnc_sensory:'#8da1aa',vnc_intrinsic:'#9a929f',vnc_motor:'#d4b383',other:'#7c858b',recorded:'#c8ced1'};
const getId=(n:NeuronSample,i=0)=>String(n.body_id??n.neuron??i);const getPos=(n:NeuronSample):[number,number,number]|null=>n.position??(n.x!=null?[n.x,n.y??0,n.z??0]:null);
function annotatedPosition(id:string,index:number,group:string):[number,number,number]{const seed=Number(id.replace(/\D/g,'').slice(-7))||index+1,r1=Math.abs(Math.sin(seed*12.9898)),r2=Math.abs(Math.sin(seed*78.233)),side=index%2?1:-1;if(group==='descending_neuron')return[(r1-.5)*1.25,-1.2-r2*2.2,Math.sin(seed)*.5];if(group==='cx_intrinsic')return[(r1-.5)*1.55,(r2-.5)*2.1,Math.sin(seed*.31)*.65];const spread=group==='visual_projection'?2.25:1.75,angle=r1*Math.PI*2,rad=.25+Math.sqrt(r2)*1.2;return[side*spread+Math.cos(angle)*rad,Math.sin(angle)*rad*.72+.45,Math.sin(seed*.77)*.75]}
type DrawNeuron={index:number;position:[number,number,number];group:string};
export default function BrainView({recording,step,activePopulation,onPopulation}:{recording:Recording;step:ReplayStep|null;activePopulation:string|null;onPopulation:(p:string|null)=>void}){
 const host=useRef<HTMLDivElement>(null),mesh=useRef<THREE.InstancedMesh|null>(null),lookup=useRef<Int32Array|null>(null);const [drawCount,setDrawCount]=useState(0);const bundle=recording.connectomeData;
 const neurons=useMemo<DrawNeuron[]>(()=>{if(bundle){const out:DrawNeuron[]=[];for(let i=0;i<bundle.count;i++){const j=i*3,x=bundle.positions[j],y=bundle.positions[j+1],z=bundle.positions[j+2];if((bundle.flags[i]&16)&&Number.isFinite(x)&&Number.isFinite(y)&&Number.isFinite(z))out.push({index:i,position:[x,y,z],group:bundle.populationNames[bundle.population[i]]??'other'})}return out}if(recording.staticNeurons.length)return recording.staticNeurons.map((n,i)=>({index:i,position:getPos(n)??annotatedPosition(getId(n,i),i,n.region??n.cell_type??'recorded'),group:n.region??n.cell_type??'recorded'}));const out:DrawNeuron[]=[];Object.entries(step?.populations??{}).forEach(([group,p])=>(p.sampled??[]).forEach((n,i)=>out.push({index:n.neuron??out.length,position:getPos(n)??annotatedPosition(getId(n,i),out.length,group),group})));return out},[recording,bundle,bundle?undefined:step?.populations]);
 useEffect(()=>{const el=host.current;if(!el||!neurons.length)return;const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x0a0d10,.045);const camera=new THREE.PerspectiveCamera(35,1,.1,100);camera.position.set(0,.2,11);const renderer=new THREE.WebGLRenderer({antialias:false,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));el.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.autoRotate=true;controls.autoRotateSpeed=.45;controls.minDistance=3;controls.maxDistance=22;scene.add(new THREE.AmbientLight(0x667080,1));const geom=new THREE.OctahedronGeometry(bundle?.count?0.018:0.06,0),mat=new THREE.MeshBasicMaterial({transparent:true,opacity:.94,vertexColors:true,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});const cloud=new THREE.InstancedMesh(geom,mat,neurons.length);cloud.instanceMatrix.setUsage(THREE.StaticDrawUsage);cloud.instanceColor=new THREE.InstancedBufferAttribute(new Float32Array(neurons.length*3),3);mesh.current=cloud;scene.add(cloud);setDrawCount(neurons.length);
 const indexMap=new Int32Array(bundle?.count??Math.max(...neurons.map(n=>n.index),0)+1);indexMap.fill(-1);lookup.current=indexMap;const box=new THREE.Box3();neurons.forEach(n=>box.expandByPoint(new THREE.Vector3(...n.position)));const center=new THREE.Vector3(),size=new THREE.Vector3();box.getCenter(center);box.getSize(size);const scale=6/Math.max(size.x,size.y,size.z,1),dummy=new THREE.Object3D();neurons.forEach((n,i)=>{dummy.position.set((n.position[0]-center.x)*scale,(n.position[1]-center.y)*scale,(n.position[2]-center.z)*scale);dummy.updateMatrix();cloud.setMatrixAt(i,dummy.matrix);if(n.index<indexMap.length)indexMap[n.index]=i});cloud.instanceMatrix.needsUpdate=true;
 let frame=0;const resize=()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(el);resize();const tick=()=>{frame=requestAnimationFrame(tick);controls.update();renderer.render(scene,camera)};tick();return()=>{cancelAnimationFrame(frame);observer.disconnect();controls.dispose();geom.dispose();mat.dispose();renderer.dispose();renderer.domElement.remove();mesh.current=null;lookup.current=null}},[neurons,bundle]);
 useEffect(()=>{const cloud=mesh.current,colors=cloud?.instanceColor?.array as Float32Array|undefined;if(!cloud||!colors)return;const top=new Map<number,number>(step?.activity?.top??[]),motorIndices=recording.header.motor_population?.indices??[],motorRates=step?.activity?.motor_rates??[],motorMap=new Map<number,number>(motorIndices.map((idx:number,i:number)=>[idx,motorRates[i]??0])),selected=step?.motor?.selected_action??step?.motor?.selected??'',contributing:number[]=recording.header.motor?.contributing?.[selected]?.indices??[],contrib=new Set(contributing);let max=1;top.forEach(v=>max=Math.max(max,v));motorRates.forEach(v=>max=Math.max(max,v));const c=new THREE.Color();neurons.forEach((n,i)=>{const focused=!activePopulation||n.group===activePopulation,rate=Math.max(top.get(n.index)??0,motorMap.get(n.index)??0),isContributor=contrib.has(n.index);c.set(palette[n.group]??palette.other);const energy=Math.min(1,rate/max);if(!focused)c.multiplyScalar(.07);else if(isContributor)c.lerp(new THREE.Color('#fff4d6'),.82);else if(rate>0)c.lerp(new THREE.Color('#fffdf5'),.18+energy*.62);else c.multiplyScalar(.18);colors[i*3]=c.r;colors[i*3+1]=c.g;colors[i*3+2]=c.b});(cloud.instanceColor as THREE.InstancedBufferAttribute).needsUpdate=true},[neurons,step,recording,activePopulation]);
 const groups=Object.entries(step?.populations??{}).sort((a,b)=>(b[1].mean_rate_hz??0)-(a[1].mean_rate_hz??0));return <div className="brain-stage"><div ref={host} className="brain-canvas"/><div className="brain-title"><span><Sparkles/> MALECNS // NEURAL ACTIVITY</span><strong>{(bundle?.count??drawCount).toLocaleString()}</strong><small>{bundle?`${drawCount.toLocaleString()} positioned neurons · real soma coordinates`:`${drawCount} sampled neurons · spatial layout annotated`}</small></div><div className="reset-view" title="Drag to rotate · scroll to zoom"><MousePointer2/> DRAG TO ORBIT <Maximize2/></div><div className="population-pills"><button className={!activePopulation?'active':''} onClick={()=>onPopulation(null)}>ALL</button>{groups.slice(0,7).map(([g,p])=><button className={activePopulation===g?'active':''} style={{'--pop':palette[g]??palette.other} as React.CSSProperties} onClick={()=>onPopulation(g)} key={g}><i/>{g.replaceAll('_',' ')} <b>{Math.round(p.mean_rate_hz??0)}</b></button>)}</div><div className="position-note">{bundle?'● MALECNS v1.0 · RECORDED COORDINATES':'◇ V1 HAS NO COORDINATES — DISPLAY LAYOUT IS ANNOTATED'}</div></div>}
