import {useEffect,useMemo,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import type {ReplayStep} from '../lib/types';

const colors=['#3ee8b5','#60a5fa','#a78bfa','#fb7185','#fbbf24','#2dd4bf'];
function fallbackPosition(id:number,index:number,total:number):[number,number,number]{const u=(index+.5)/Math.max(total,1),phi=Math.acos(1-2*u),theta=Math.PI*(1+Math.sqrt(5))*index,r=2.4*(.68+.32*Math.sin(id*.013)**2);return [r*Math.sin(phi)*Math.cos(theta)*(.7+.2*Math.sin(phi)),r*Math.cos(phi)*1.25,r*Math.sin(phi)*Math.sin(theta)]}
export default function BrainView({step}:{step:ReplayStep|null}){
 const host=useRef<HTMLDivElement>(null), points=useRef<THREE.Points|null>(null);const [filter,setFilter]=useState('all');
 const groups=useMemo(()=>Object.entries(step?.populations??{}),[step]);
 const neurons=useMemo(()=>{const out:{id:number;rate:number;group:string;pos?:[number,number,number]}[]=[];groups.forEach(([group,p])=>(p.sampled??[]).forEach((n,i)=>out.push({id:Number(n.body_id??n.neuron??i),rate:Number(n.rate_hz??n.activity??p.mean_rate_hz??0),group,pos:n.position??(n.x!=null?[n.x,n.y??0,n.z??0]:undefined)})));(step?.neurons??[]).forEach((n,i)=>out.push({id:Number(n.body_id??n.neuron??i),rate:Number(n.rate_hz??n.activity??0),group:n.region??n.cell_type??'recorded',pos:n.position??(n.x!=null?[n.x,n.y??0,n.z??0]:undefined)}));return filter==='all'?out:out.filter(n=>n.group===filter)},[groups,step,filter]);
 useEffect(()=>{const el=host.current;if(!el)return;const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(0,1,8);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));el.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.autoRotate=true;controls.autoRotateSpeed=.35;const grid=new THREE.GridHelper(7,14,0x183238,0x102126);grid.position.y=-3;scene.add(grid);const geometry=new THREE.BufferGeometry();const material=new THREE.PointsMaterial({size:.075,transparent:true,opacity:.92,vertexColors:true,sizeAttenuation:true,blending:THREE.AdditiveBlending});const cloud=new THREE.Points(geometry,material);points.current=cloud;scene.add(cloud);let id=0;const resize=()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()};const tick=()=>{id=requestAnimationFrame(tick);controls.update();renderer.render(scene,camera)};new ResizeObserver(resize).observe(el);resize();tick();return()=>{cancelAnimationFrame(id);controls.dispose();geometry.dispose();material.dispose();renderer.dispose();renderer.domElement.remove()}},[]);
 useEffect(()=>{const p=points.current;if(!p)return;const pos=new Float32Array(neurons.length*3),col=new Float32Array(neurons.length*3);const max=Math.max(...neurons.map(n=>n.rate),1);neurons.forEach((n,i)=>{const xyz=n.pos??fallbackPosition(n.id,i,neurons.length);pos.set(xyz,i*3);const c=new THREE.Color(colors[Math.max(0,groups.findIndex(([g])=>g===n.group))%colors.length]);c.lerp(new THREE.Color('#fff3c4'),Math.min(1,n.rate/max)*.65);col.set([c.r,c.g,c.b],i*3)});p.geometry.setAttribute('position',new THREE.BufferAttribute(pos,3));p.geometry.setAttribute('color',new THREE.BufferAttribute(col,3));p.geometry.computeBoundingSphere()},[neurons,groups]);
 const recordedPositions=neurons.some(n=>n.pos);
 return <div className="brain-wrap"><div ref={host} className="brain-canvas"/><div className="brain-overlay"><div className="legend"><i className="observed"/>Observed activity <i className="annotated"/>Engineering layout</div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All populations</option>{groups.map(([g])=><option key={g}>{g}</option>)}</select></div><div className="brain-note">{recordedPositions?'Recorded neuron coordinates':'Spatial positions unavailable in v1 — deterministic layout is an engineering annotation.'}</div></div>
}
